### ISSUE TITLE
TODO's

### ISSUE THREAD

**Issue by ajpelu** [ajpelu/evi_berchules#1]
## GIS 
* [] conseguir información geográfica de la acequia de Bérchules
* [] Crear mapa de distribución de acequia 
* [] Mapa de distribución de los enebrales pastizales 

        * [] Mapa de vegetación de SN? 
* [] Centroides de los pixeles de MODIS 

## Remote Sensing 
* GEE script para bajar los datos
